[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "B19SNU7Gm8VeeJ6GsQgjnzdXgC4QaxrX3EC4udk8HHF2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/thomas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
